### ISSUE TITLE
A binding for C-u C-c

### ISSUE THREAD

**Issue by aspiwack** [jyp/boon#29]
I've come across a mode that binds something useful to `C-u C-c C-<something>`. I could work around this with some custom configuration, but in the spirit of being as compatible with existing modes as possible, I'm wondering if it would be worth adding a binding that resolves to `C-u C-c C-`.

I can suggest using `C` for this.

**Comment by jyp** [comment]
I've just fixed `boon-c-god`, so that it now honours prefix arguments. @aspiwack Could you test that it works? (By default the universal prefix argument is bound to `~`, so you would have to type `~ c <something>`. Then if you want to use a fixed value for the prefix argument it is just a matter of defining a command which calls `boon-c-god` appropriately.

**Comment by aspiwack** [comment]
Indeed. I wasn't aware of `~`, my bad. This should do :) .

**Comment by jyp** [comment]
To be sure, prefix arguments did not work with `bood-c-god`. Thanks for the bug report :+1:
