### ISSUE TITLE
No such file or directory, powerline

### ISSUE THREAD

**Issue by bernardjoseph** [jyp/boon#85]
I do not have powerline installed, but sometimes Emacs wants to load powerline, e. g. when I call `describe-funtion` for a boon function the first time with completion. `describe-function` has an autoload functionality which loads all boon-* files, when I do autocompletion for a boon-* function. Then the error message

    eval-buffer: Cannot open load file: No such file or directory, powerline

appears, because powerline is not installed. I helped myself with

    (require powerline nil t)

instead of `(require powerline)` in the file `boon-powerline`. And now the file `boon-powerline` can also be compiled without having powerline installed.

**Comment by jyp** [comment]
But do you require boon-powerline? You should not do that if you don't want the powerline functionality. I feel that I'm missing some basic info.

**Comment by berndjr** [comment]
I do not require powerline and I have not installed powerline, but the `boon-powerline` library requires powerline. Then I do not need the `boon-powerline` library and the `boon-powerline` library is not loaded. So far there is no problem. But now I want to see the documentation of some boon function, which is not in the `boon-powerline` library, e. g. `boon-quit`. I call `describe-function` and type `boon-quit` into the minibuffer. After pressing Enter the error message occurs, because `describe-function` implicitly tries to load the `boon-powerline` library, which requires powerline. This happens only the first time after starting Emacs. The next calls of `describe-function` work without error message.

**Comment by jyp** [comment]
Fixed.
